/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memorymatchingremake;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author Vatsav
 */
public class GameFrame extends JFrame {
    private JButton[] game;
    private List<Integer> map;
    private Container cont;
    private int clickNo;
    private int prevClick;
    private int fails;
    private int pairs;
    private boolean firstClick;
    Instant start;
    
    Icon burger;
    Icon flash;
    Icon fries;
    Icon marvel;
    Icon cd;
    Icon starbucks;
    Icon pizza;
    Icon icecream;

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        super("Memory Matching");
        
        burger = new ImageIcon("pictures\\burger.png");
        flash = new ImageIcon("pictures\\flash.png");
        fries = new ImageIcon("pictures\\fries.png");
        marvel = new ImageIcon("pictures\\marvel.png");
        cd = new ImageIcon("pictures\\cd.png");
        starbucks = new ImageIcon("pictures\\starbucks.png");
        pizza = new ImageIcon("pictures\\pizza.png");
        icecream = new ImageIcon("pictures\\icecream.png");
        
        game = new JButton[16];
        map = new ArrayList<Integer>(16);
        clickNo = 1;
        prevClick = 0;
        fails = 0;
        pairs = 0;
        firstClick = true;
        
        cont = getContentPane();
        cont.setLayout(new GridLayout(4, 4));
        ButtonHandler bh = new ButtonHandler();
        for(int i = 0; i < 16; i++){
            map.add(i);
            game[i] = new JButton();
            cont.add(game[i]);
            game[i].addActionListener(bh);
        }
        Collections.shuffle(map);
//        for(int i = 0; i < 16; i++)
//            assignPicture(i, map.get(i));
        setSize(350, 350);
        setVisible(true);        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }
    
    private void assignPicture(int bn, int i){
        switch(i){
            case 0:
            case 15: game[bn].setIcon(burger);
                break;
                
            case 1: 
            case 14: game[bn].setIcon(pizza);
                break;
                
            case 2:
            case 13: game[bn].setIcon(cd);
                break;
                
            case 3:
            case 12: game[bn].setIcon(flash);
                break;
                
            case 4:
            case 11: game[bn].setIcon(fries);
                break;
                
            case 5:
            case 10: game[bn].setIcon(icecream);
                break;
                
            case 6:
            case 9: game[bn].setIcon(marvel);
                break;
                
            case 7:
            case 8: game[bn].setIcon(starbucks);
                break;
        }
    }
    
    private void assignDisabledPicture(int bn, int i){
        switch(i){
            case 0:
            case 15: game[bn].setDisabledIcon(burger);
                break;
                
            case 1: 
            case 14: game[bn].setDisabledIcon(pizza);
                break;
                
            case 2:
            case 13: game[bn].setDisabledIcon(cd);
                break;
                
            case 3:
            case 12: game[bn].setDisabledIcon(flash);
                break;
                
            case 4:
            case 11: game[bn].setDisabledIcon(fries);
                break;
                
            case 5:
            case 10: game[bn].setDisabledIcon(icecream);
                break;
                
            case 6:
            case 9: game[bn].setDisabledIcon(marvel);
                break;
                
            case 7:
            case 8: game[bn].setDisabledIcon(starbucks);
                break;
        }
    }
    
    private void checkWin(){
        if(pairs == 8){
            long time = Duration.between(start, Instant.now()).toSeconds();
            JOptionPane.showMessageDialog(null, "Game over. You made " + fails + " mistakes and took " + time + " seconds");
        }     
    }
    
    
    private class ButtonHandler implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            Object o = e.getSource();
            int ind = 0;
            for(int i = 0; i < 16; i++){
                if(o == game[i])
                    ind = i;
            }
            if(firstClick){
                start = Instant.now();
                firstClick = false;
            }
            if(clickNo == 1){
                assignPicture(ind, map.get(ind));
                assignDisabledPicture(ind, map.get(ind));
                game[ind].setEnabled(false);
                System.out.println(map.get(ind));
                prevClick = ind;
                clickNo = 2;
            }
            else{
                assignPicture(ind, map.get(ind));
                System.out.println("Prev: " + prevClick + "  Cur: " + ind);
                if(map.get(prevClick) + map.get(ind) == 15){
                    pairs++;
                    JOptionPane.showMessageDialog(null, "Match made");
                    game[prevClick].setDisabledIcon(null);
                    game[ind].setDisabledIcon(null);
                    game[ind].setEnabled(false);
                    checkWin();
                }
                else{
                    fails++;
                    JOptionPane.showMessageDialog(null, "Mismatch");
                    game[prevClick].setEnabled(true);
                    game[ind].setEnabled(true);
                    game[prevClick].setIcon(null);
                    game[ind].setIcon(null);
                }
                
                clickNo = 1;
            }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
